spring:
  application:
    name: MoneyCoach

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver

  # Скрипты инициализации
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath: data.sql

# Активный профиль задаётся через JVM-параметр:
# -Dspring.profiles.active=prod или test
